<?php

use Livewire\Attributes\Layout;
use Livewire\Volt\Component;

new #[Layout('layouts.guest')] class extends Component
{
    //
}; ?>

<div x-data="{ recovery: false }">
    <div class="mb-6 text-center">
        <span class="mx-auto inline-flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path stroke-linecap="round" stroke-linejoin="round"
                    d="M12 3 4.5 6v5.25c0 4.77 3.22 8.66 7.5 9.75 4.28-1.09 7.5-4.98 7.5-9.75V6L12 3Zm-2.25 9 1.5 1.5 3-3" />
            </svg>
        </span>
        <h1 class="mt-3 text-xl font-bold text-slate-900">Two-factor authentication</h1>
        <p class="mt-1 text-sm text-slate-500" x-show="! recovery">
            Enter the 6-digit code generated by your authenticator app.
        </p>
        <p class="mt-1 text-sm text-slate-500" x-show="recovery" x-cloak>
            Enter one of your emergency recovery codes.
        </p>
    </div>

    <form method="POST" action="{{ route('two-factor.login.store') }}" class="space-y-5">
        @csrf

        <div x-show="! recovery">
            <x-input-label for="code" value="Authentication code" />
            <x-text-input id="code" name="code" type="text" inputmode="numeric"
                autocomplete="one-time-code" maxlength="6"
                class="mt-1 block w-full text-center text-xl tracking-[0.35em]" autofocus />
            <x-input-error :messages="$errors->get('code')" class="mt-2" />
        </div>

        <div x-show="recovery" x-cloak>
            <x-input-label for="recovery_code" value="Recovery code" />
            <x-text-input id="recovery_code" name="recovery_code" type="text"
                autocomplete="one-time-code" class="mt-1 block w-full font-mono" />
            <x-input-error :messages="$errors->get('recovery_code')" class="mt-2" />
        </div>

        <x-primary-button class="w-full justify-center">Verify and continue</x-primary-button>

        <button type="button" @click="recovery = ! recovery"
            class="w-full text-center text-sm font-semibold text-blue-600 transition hover:text-blue-800">
            <span x-show="! recovery">Use a recovery code</span>
            <span x-show="recovery" x-cloak>Use an authentication code</span>
        </button>
    </form>
</div>
